"""Export service for generating reports."""
from __future__ import annotations

import json
from typing import Any, Dict

from ..db.models import Case, ChecklistItem, Risk, TimelineItem


def export_case_json(case_data: Dict[str, Any]) -> str:
    """Export case data as JSON."""
    return json.dumps(case_data, indent=2)


def export_case_markdown(case_data: Dict[str, Any]) -> str:
    """Export case data as Markdown."""
    case = case_data.get("case", {})
    checklist = case_data.get("checklist", [])
    timeline = case_data.get("timeline", [])
    risks = case_data.get("risks", [])
    
    md = f"""# {case.get('title', 'Case Report')}

## Summary

{case.get('summary', 'No summary available.')}

**Scenario:** {case.get('scenario', 'N/A').replace('_', ' ').title()}  
**Case ID:** {case.get('id', 'N/A')}

---

## Checklist

"""
    
    for idx, item in enumerate(checklist, 1):
        status_icon = "✅" if item.get("status") == "done" else "⏳" if item.get("status") == "in_progress" else "📋"
        md += f"### {idx}. {status_icon} {item.get('label', 'Item')}\n\n"
        md += f"**Status:** {item.get('status', 'todo')}  \n"
        md += f"**Notes:** {item.get('notes', 'No notes.')}\n\n"
        
        if item.get('evidence_chunk_ids'):
            md += f"**Evidence chunks:** {len(item.get('evidence_chunk_ids', []))}\n\n"
        md += "---\n\n"
    
    md += "## Timeline\n\n"
    
    for idx, item in enumerate(timeline, 1):
        md += f"### {idx}. {item.get('label', 'Task')}\n\n"
        if item.get('due_date'):
            md += f"**Due:** {item.get('due_date')}  \n"
        md += f"**Owner:** {item.get('owner', 'user')}  \n"
        md += f"**Notes:** {item.get('notes', 'No notes.')}\n\n"
        md += "---\n\n"
    
    md += "## Risks\n\n"
    
    for idx, item in enumerate(risks, 1):
        severity = item.get('severity', 'medium')
        severity_icon = "🔴" if severity.lower() == "high" else "🟡" if severity.lower() == "medium" else "🟢"
        md += f"### {idx}. {severity_icon} {item.get('statement', 'Risk')}\n\n"
        md += f"**Severity:** {severity.upper()}  \n"
        md += f"**Category:** {item.get('category', 'general')}  \n"
        md += f"**Reason:** {item.get('reason', 'No reason provided.')}\n\n"
        md += "---\n\n"
    
    md += "\n---\n\n*Generated by LifeBridge - AI-Powered Cross-Border Mobility Assistant*\n"
    
    return md

